/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codemercs_iow_IowKit */

#ifndef _Included_com_codemercs_iow_IowKit
#define _Included_com_codemercs_iow_IowKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    openDevice
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit_openDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    closeDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_codemercs_iow_IowKit_closeDevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    write
 * Signature: (JJ[I)J
 */
JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit_write
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    read
 * Signature: (JJJ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_codemercs_iow_IowKit_read
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    readNonBlocking
 * Signature: (JJJ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_codemercs_iow_IowKit_readNonBlocking
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    readImmediate
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_codemercs_iow_IowKit_readImmediate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    getNumDevs
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit_getNumDevs
  (JNIEnv *, jclass);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    getDeviceHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit_getDeviceHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    getProductId
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit_getProductId
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    getRevision
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit_getRevision
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    getSerialNumber
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_codemercs_iow_IowKit_getSerialNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    setTimeout
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit_setTimeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    setWriteTimeout
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit_setWriteTimeout
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    cancelIo
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_codemercs_iow_IowKit_cancelIo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_codemercs_iow_IowKit_version
  (JNIEnv *, jclass);

/*
 * Class:     com_codemercs_iow_IowKit
 * Method:    getThreadHandle
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_codemercs_iow_IowKit_getThreadHandle
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
